### ISSUE TITLE
Stage 0 - Create a repository checklist

### ISSUE THREAD

**Issue by Erulathra** [S1NU5-P1/MS-SS-TPW-Project#1]
## Create a repository checklist - (WIP)

- [x] the task provides required feedback and has been submitted (needs grading)
- [x] the ability to clone the repository to the teacher's computer
- [x] there is README.md formatted as expected
- [x] `README.md` contains required information
- [x] build succeeded
- [x] all UTs are green
