### ISSUE TITLE
Project Stage 1 Checklist (WIP)

### ISSUE THREAD

**Issue by Erulathra** [S1NU5-P1/MS-SS-TPW-Project#3]
- [x] all UT are green
- [x] build succeeded
- [x] text is in C# and use .NET
- [x] Dependency injection (additional framework is not required)
- [x] Mock is used for testing purposes (expected but not required)
- [x] Unit Test - layers are tested independently using abstract API
- [x] `Presentation` layer is clearly stated using language terms only
- [x] `Logic` layer is clearly stated using language terms only
- [x] `Logic` API is clearly stated
- [x] `Logic` uses only the abstract `Data` layer API
- [x] `Data` API is abstract
- [x] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [x] mvvm and xaml is applied to implement GUI
- [x] reactive and interactive user interaction for user (operator) communication
- [x] reactive and interactive programming is used for layers communication
- [x] Object model representing process data
